version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}

  tests:
    image: python:3.12-slim
    depends_on:
      - fastapi
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
    command: >
      sh -c "pip install --no-cache-dir -r ./requirements.txt &&
        pytest -v -s"
