version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    image: python:3.12-slim
    depends_on:
      fastapi:
        condition: service_healthy
    working_dir: /tests
    volumes:
      - ./tests:/test
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SECRET=${SECRET}
    command: >
      sh -c "pip install --no-cache-dir -r /tests/requirements.txt &&
        pytest -v -s"
