name: Expense Tracker API tests

on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Rub Docker tests
      run: |
        ls
        docker build -t docker-api-test .
        docker run --rm \
          -e EMAIL=${{ vars.EMAIL }} \
          -e PASSWORD=${{ secrets.PASSWORD }}
          -e SECRET=${{ secrets.SECRET }}



